/**
 * Embedded evaluation rules based on the repository's `rules.md` reference.
 * The relevant rule family is selected for each analysis mode so agents do
 * not have to infer whether they are reviewing fairness, test gaps, or a
 * solution defect from a generic rubric.
 */

const GUIDELINES_TEXT = [
  "## The problem description (aka the task)",
  "P1: Aligns with the repo's philosophy.",
  "P2: Self-contained — solvable from the repo and description alone.",
  "P3: Clear, concise, and unambiguous — describes what to build or fix without leaving points for guessing.",
  "P4: Verifiable — success is objectively testable.",
  "P5: Not prescriptive — does not leak the solution.",
  "",
  "## The tests",
  "T1: They highlight the missing or incorrect behavior and fail before the solution.",
  "T2: They are deterministic and terminating.",
  "T3: They assert the required public behavior strongly and diagnostically.",
  "T4: They cover the requested behavior and justified edge cases.",
  "T5: They do not check unspecified or undiscoverable behavior.",
  "T6: They do not over-pin output, representation, timing, or wording.",
  "T7: They preserve valid alternative implementations and public integration paths.",
  "T8: They keep fixtures, reporting, and the evaluation environment viable.",
  "",
  "## The solution",
  "S1: The solution meets all requirements and preserves required public behavior.",
  "S2: It has no regressions and follows existing repository patterns.",
  "S3: It contains no irrelevant changes.",
  "S4: It contains no dead code, unexplained scaffolding, or avoidable implementation coupling.",
].join("\n");

const FAIRNESS_RULES_TEXT = [
  "# Fairness vs. unfairness",
  "",
  "## Core standard",
  "",
  "A test is fair when it checks behavior required by the task description, clearly established by an existing public repository contract, or directly observable by a user or caller. A test is unfair when a reasonable implementation can satisfy the task and the repository's public contract but fail because the test chooses an undocumented implementation detail.",
  "",
  "The reference implementation, a convenient fixture, a neighboring private helper, and a test harness are evidence at most. They are not the specification by themselves.",
  "",
  "For every assertion, ask:",
  "",
  "1. What exact prompt requirement or established public contract supports it?",
  "2. What can a user, caller, or public API observe?",
  "3. Could two competent implementations satisfy that contract while differing on this assertion?",
  "4. Does the fixture and observation point preserve all repository-valid implementation paths?",
  "5. Would the assertion catch a materially incorrect behavior rather than merely a different implementation?",
  "",
  "If two competent implementations can satisfy the contract while differing on the assertion, and the prompt/repository does not select one outcome, the assertion is unfair. Rewrite it around the shared semantic behavior or remove it.",
  "",
  "## Fair",
  "",
  "- Verifies behavior explicitly required by the task.",
  "- Verifies behavior exposed by an existing public API or an established public repository convention.",
  "- Checks the visible result, caller-visible state, required side effect, or documented data contract.",
  "- Requires a new exported name, field, control, attribute, label, key, or option only when the task names it or the existing public API already establishes it.",
  "- Allows equivalent public integration paths, helper delegation, service boundaries, and implementation structures.",
  "- Allows additional valid fields or metadata when the contract requires only a subset of structured output.",
  "- Checks required relationships such as preservation, isolation, ordering, association, or eventual refresh without guessing unrelated concrete values.",
  "- Normalizes or parses equivalent syntax before comparing semantics.",
  "- Accepts clear failure behavior when the contract does not prescribe one exact error representation.",
  "- Waits or polls for an eventual result when synchronous completion is not part of the contract.",
  "- Uses fixtures that preserve real state invariants, module shape, exported references, and valid repository behavior.",
  "- Observes a public effect rather than requiring one internal call or observation point.",
  "- Separates a fair behavioral assertion from an unrelated unsupported co-assertion.",
  "",
  "## Unfair",
  "",
  "### Undocumented implementation choices",
  "",
  "- Requires a private helper, internal class, private state field, or unmentioned file path.",
  "- Requires a particular module boundary, import path, direct platform call, algorithm, call order, or failure-injection primitive when another repository-valid path produces the same effect.",
  "- Requires a new method, constructor, property, export, argument shape, registry key, option ID, or configuration name that the task does not specify and the repository does not already expose publicly.",
  "- Treats the reference implementation's structure, naming, defaults, or minimal serialization as mandatory.",
  "",
  "### Representation instead of semantics",
  "",
  "- Compares an entire object, document, mapping, or array to a minimal expected serialization when the contract requires only selected fields, values, preservation, or relationships.",
  "- Rejects additional valid fields or metadata that do not weaken the required behavior.",
  "- Pins a concrete container or materialization type when the contract specifies the contents or tabular behavior but not the wrapper type.",
  "- Requires a particular field location, source file, interface placement, AST node shape, type alias, type spelling, quote style, whitespace, line break, token adjacency, generated identifier, or code length.",
  "- Requires exact row/group ordering, result cardinality, or per-item counting when the contract does not define that ordering or granularity.",
  "- Requires literal source words to prove behavior that can be checked by compiling, parsing, rendering, executing, or inspecting the public result.",
  "",
  "### Values and relative language",
  "",
  "- Infers an exact value from words such as current, latest, selected, next, matching, appropriate, or stable when only a relationship or effect is required.",
  "- Treats an example, default, neighboring helper behavior, or one fixture value as a universal requirement.",
  "- Requires a particular normalization or encoding strategy when multiple representations preserve the required meaning.",
  "- Requires an incidental no-op artifact, such as whether an empty file, directory, cache entry, history item, or output record exists, when only content/state/reuse/non-duplication is contractual.",
  "",
  "### Counts, categories, and interactions",
  "",
  "- Requires an exact count without a specified counting unit. A count might be per input, field, item, target, rule, match, category, finding, log record, or operation.",
  "- Requires a repair or mutation count without specifying whether it reports findings before the change or findings remaining afterward.",
  "- Assumes diagnostic categories are mutually exclusive or overlapping when the task does not define that relationship.",
  "- Assumes a majority, plurality, unanimity, or other consensus rule without the prompt defining what dissenting values mean.",
  "- Assumes duplicate detection is per collection or global across collections without the contract defining the scope.",
  "- Resolves an interaction between two requirements by intuition—for example, whether a missing optional value skips only value checks or an entire combined rule, whether a cache is reused across a changed input, or whether a target-level check still runs when a value path is absent.",
  "- Requires one line, one repeated term, one log record, or one message per underlying issue when aggregate reporting is equally compliant.",
  "",
  "### Configuration schemas and boundaries",
  "",
  "- Invents a field type, collection shape, omitted-field default, unknown-key policy, coercion rule, extension-based parser dispatch, or cross-field constraint.",
  "- Requires a string-only name, boolean-only flag, particular list schema, strict rejection of extra top-level keys, or rejection of an inverted range when the task does not establish that schema choice.",
  "- Invents acceptance or rejection rules for unspecified malformed, missing, nullish, Unicode, unusually large, boolean-like, numeric, platform-specific, symlink, or missing-parent inputs.",
  "- Assumes a strict validation policy, unlimited policy, coercion policy, or normalization policy that the task does not state.",
  "- Selects one behavior at an underspecified boundary such as dry-run, preview, no-op, conflict, rollback, cache reuse, preflight, or a state transition.",
  "- Assumes mathematical edge values or non-finite values have a particular ordering or rejection policy when the prompt specifies only ordinary finite bounds or numeric behavior.",
  "",
  "### Errors, messages, and timing",
  "",
  "- Requires an exact exception class, error code, message text, punctuation, capitalization, embedded input, basename, or log wording when the contract only requires failure, a clear error, or reporting.",
  "- Requires validation during construction rather than evaluation, or vice versa, when the public contract does not specify timing.",
  "- Requires a callback to return a promise, be fully settled on return, or update immediately when the contract promises only an eventual effect.",
  "- Uses a small wall-clock threshold as a functional requirement without a stated performance contract; such limits are often platform- and load-dependent.",
  "- Requires a particular signal, alarm, subprocess ceiling, poll interval, viewport size, or platform-specific safety mechanism when only bounded or fail-fast behavior is required.",
  "- Requires one exact logging vocabulary when the operation can be reported clearly in equivalent wording.",
  "- Rejects one permitted failure path when the task explicitly allows alternatives such as load-time rejection or evaluation-time violation.",
  "",
  "### Expressions and embedded languages",
  "",
  "- Assumes an unlisted builtin, operator, method, container type, mapping shape, mutability rule, or context binding in a restricted expression language.",
  "- Requires a particular representation for context variables when the task names their meaning but not whether they are mappings, models, lists, tuples, or another equivalent public value.",
  "- Requires a dangerous expression to be rejected during parsing when the contract also permits prohibited constructs to be rejected during evaluation, or vice versa.",
  "- Treats one expression-evaluation cardinality as mandatory when a multi-match rule could reasonably be evaluated once per target, once per rule, or once per resolved value.",
  "",
  "### UI, lifecycle, and harness coupling",
  "",
  "- Requires exact DOM hierarchy, CSS classes, selectors, test/data attributes, native tags, hidden text, hidden-shim text, ARIA attributes, focus order, keyboard traversal, or mock-specific control counts when the task specifies only a user-facing action or visible result.",
  "- Requires an initial focus, default Enter action, Tab order, button order, or immediate control visibility when the prompt only names the available choices.",
  "- Requires a component to expose a particular model API merely so the test can mutate it, when the behavior can be exercised through the real public UI or caller flow.",
  "- Exercises a detached constructor, unmounted widget, partial view, or inactive editor while asserting behavior qualified by an active or mounted production context.",
  "- Uses a mock that omits valid exports, changes the shape of real state, reassigns exported arrays/objects, or patches a source module while the application holds an imported binding.",
  "- Requires a fake collaborator to implement hidden, newly invented hooks instead of using the repository's existing public extension point.",
  "- Uses incomplete fixtures that cause a valid implementation to fail before the behavior under test is reached.",
  "- Accepts only a hidden harness's import path, shim, serialized text, or mock behavior rather than the repository's public contract.",
  "",
  "### Mixed assertions",
  "",
  "A test can contain both fair and unfair assertions. Do not discard the entire behavioral goal automatically. Keep the assertion that checks the required observable effect and remove or relax only the unsupported value, representation, timing, API, side effect, or harness assumption. Conversely, a test that looks behaviorally useful is still unfair overall if one mandatory co-assertion rejects a valid implementation.",
  "",
  "## Scope and alternatives",
  "",
  "Preserve every qualifier in the prompt. A requirement for aware values, naive values, all-day values, one mode, one target state, or one lifecycle phase does not automatically apply to every representation or phase. Do not transfer a rule from one subtype to another, or require a changed wall time, timezone, normalization, or side effect outside the stated scope.",
  "",
  "When the prompt expressly allows more than one outcome or phase, a fair test must accept every permitted alternative. Do not force one load/evaluation phase, one error form, or one integration route merely because it is simpler to assert. Conversely, do not call a test unfair merely because it rejects behavior that the prompt explicitly forbids; distinguish an actual contract prohibition from an unstated mechanism used to enforce it.",
  "",
  "## Public repository evidence",
  "",
  "Existing source code can establish a public contract when the behavior is exposed through a public API, documented UI, established file format, or stable user-facing convention. It does not make every internal branch or helper behavior contractual.",
  "",
  "Use the closest relevant analogues, not an arbitrary nearby example. If analogues disagree, or if the only evidence is private implementation structure, do not pin the detail. A visible security or compatibility rule can make a boundary requirement discoverable, but an unrelated helper's default does not automatically define a new feature.",
  "",
  "A repository convention can justify an exact detail only when it is public, stable, directly relevant, and unambiguous. It does not justify a hidden import-binding assumption, a particular cache mutation path, or a newly introduced collaborator method merely because one implementation uses it.",
  "",
  "## Test strength versus test fairness",
  "",
  "A test may be fair but too weak. For example, a color assertion that searches the entire viewport may pass because an unrelated cell has that color; a message check may find text unrelated to the operation; a timezone assertion may check the destination representation without checking preservation of the underlying instant. These are coverage or observation defects, not reasons to impose a new implementation detail.",
  "",
  "Strengthen such tests by observing the correct public target, associating the result with the operation, and checking the semantic invariant. Do not strengthen them by requiring private state, exact source form, or one architecture.",
  "",
  "A failed setup and a failed behavioral assertion are also different. If a shared fixture crashes before the feature is observed, or an observer renders the wrong widget/viewport after locating a valid result, that is a broken test harness—not evidence of an implementation gap. If the fixture reaches the public behavior but rejects a valid alternative representation or integration path, that is a test/contract mismatch. Neither should be treated as a fair behavioral requirement.",
].join("\n");

const GAP_RULES_TEXT = [
  "# Gaps in tests",
  "",
  "This section defines missing or weak test coverage. It is separate from fairness: a test may be fair but too weak, or a proposed gap may describe a real missing behavior but be unfairly asserted. Use `--GAPS--` records for test-side deficiencies and `T<num>` labels for the test-quality dimension involved.",
  "",
  "## `--GAPS--` candidate rules",
  "",
  "A `--GAPS--` block is a candidate, not an automatic requirement. Accept it only after checking the prompt/public contract, the validity of its fixture, the public observation, and whether a plausible incomplete implementation can evade the current suite. Keep the candidate distinct, actionable, and fair.",
  "",
  "A genuine gap must be:",
  "",
  "- grounded in a specific task requirement or clear public contract;",
  "- distinct from other candidates;",
  "- observable through a public behavior;",
  "- expressible without private implementation assumptions;",
  "- meaningful enough that a plausible incomplete implementation could pass without it; and",
  "- fair to multiple reasonable implementations.",
  "",
  "Do not report optional coverage ideas, generic requests for more negative tests, speculative edge cases, or details that are merely convenient to assert. Edge cases are valuable when the task requires them or the public contract clearly implies them; otherwise they are not gaps.",
  "",
  "When a candidate's first wording is too specific, reformulate it around the semantic requirement. For example, require preservation of required data rather than a minimal serialized object, required ordering relationships rather than an incidental sort order, and a reported failure rather than an arbitrary message or exception path. If no fair formulation remains, drop the candidate.",
  "",
  "An empty candidate list is correct when no proposed check survives these rules.",
  "",
  "## T<num> metrics for test gaps",
  "",
  "`T` metrics describe weaknesses in the tests or test harness. They do not, by themselves, claim that the implementation is wrong. Combine labels when one gap has more than one weakness, for example `T3/T4` for a weak assertion that also misses a required branch.",
  "",
  "### T1 — fixture and setup reliability",
  "",
  "The test setup must be valid and must reach the behavior under test. Do not count a malformed fixture, missing required outer field, stale object, invalid lifecycle state, incomplete mock, unavailable dependency, or setup exception as an implementation failure. Repair the fixture or isolate the environmental problem while preserving meaningful regression coverage.",
  "",
  "### T2 — deterministic and terminating execution",
  "",
  "Tests must not depend on wall-clock races, unseeded randomness, scheduler order, loose configurable timeouts, unbounded polling, infinite expressions, deadlocking workers, or machine-dependent thresholds. Use controlled clocks, synchronization, bounded waits, deterministic inputs, and an explicit failure when the bound is exceeded.",
  "",
  "### T3 — assertion strength and diagnostic specificity",
  "",
  "Assertions must prove the required public result, state, count, relationship, side effect, error channel, or continuation. Avoid label-only output checks, whole-output inequality, stale/unrelated messages, generic exceptions, aggregate flags that hide individual failures, and mixed fixtures that allow a wrong implementation to pass. When diagnostics are contractual, verify that they identify the relevant target/field/rule without pinning exact wording.",
  "",
  "### T4 — required behavior and edge coverage",
  "",
  "Cover every prompt sentence, explicit prohibition, public entry point, supported backend/format, lifecycle path, and justified boundary. Include meaningful falsey values, aliases, malformed input, empty/missing values, repeated operations, nested/list members, persistence/reload, failure/rollback, and cross-feature interactions when the contract supports them. Do not turn unspecified hypothetical cases into gaps.",
  "",
  "### T5 — interaction-protocol neutrality",
  "",
  "Drive interactive and UI behavior through the public user contract, not one prompt choreography, ordinal answer sequence, hidden control, private widget, exact call count, or implementation-specific selection protocol. Test the resulting public state/effect and accept equivalent accessible flows unless the prompt fixes the protocol.",
  "",
  "### T6 — evaluation-environment viability",
  "",
  "The required base/regression command must be runnable in the prescribed offline, non-root, permission, dependency, and repository environment. A broad unrelated suite that fails before reaching the touched area is a harness blocker, not evidence against the solution. Keep genuine touched-area regression tests while removing environmental false failures.",
  "",
  "### T7 — representation and expectation fairness",
  "",
  "Do not require a reference-only rendering, full untruncated value, exact field placement, parser spelling, DOM structure, output order, or concrete serialization when the public contract permits equivalent results. If a display/format detail is required, assert only that specified semantic detail and use fixtures that do not accidentally test an unrelated truncation or layout limit.",
  "",
  "### T8 — complete and honest reporting",
  "",
  "Do not use fail-fast execution when the task requires all diagnostics. Every real test must run and appear in the report/JUnit output. Distinguish setup failures, timeouts/OOMs, environment failures, and behavioral assertion failures; never synthesize a collection of failures after a wrapper aborts or let an unrelated warning satisfy the current test.",
  "",
  "## Test-gap calibration from the corpus",
  "",
  "The following rules are distilled from the cleaned unfair-test, gap-report, and rubric corpus. They apply when proposing a test, auditing a reported gap, or judging a solution. They refine the core standard above; they do not create requirements that the task prompt leaves open.",
  "",
  "### Contract-first gap triage",
  "",
  "- A reported gap is actionable only when it identifies a concrete prompt/public-contract requirement, a plausible incomplete implementation that would evade the current tests, and a public observation that distinguishes the behaviors. “More coverage would be nice” is not a gap.",
  "- During Gap Finder analysis, use `agent_prompt.md` and observable repository behavior as the specification. Do not use `test.patch`, `solution.patch`, a hidden-test name, or reference-only structure to invent a requirement; those may help locate a scenario only after the public contract has independently grounded it.",
  "- Separate three questions: is the behavior required, is the current suite blind to it, and is the proposed test fair? A candidate can be a real missing behavior but still need its assertion rewritten to remove an unfair value, API, timing, fixture, or harness assumption.",
  "- Keep the semantic core when possible. If a candidate fairly proves preservation, isolation, rejection, ordering, or an effect but also pins a message, count, serialization, private method, or prompt sequence, relax only the unsupported co-assertion rather than discarding the whole candidate.",
  "- Do not infer a requirement from solver convergence, the golden solution, a hidden test name, a reference branch, a default chosen by one implementation, or a reviewer’s preferred design. Those are investigation clues only.",
  "- If a candidate exposes a genuine ambiguity—consensus versus plurality, pre- versus post-repair counts, omitted-default semantics, cross-format collision policy, preset precedence, hunk grouping, or a recurrence alias grammar—clarify the prompt or accept all reasonable outcomes. Do not silently turn one interpretation into a hidden requirement.",
  "- Negative tests require an actual prohibition, guard, invalid state, isolation rule, or failure policy. Do not turn ordinary positive coverage into a negative gap merely because a second wrong implementation is imaginable.",
  "",
  "### Assertion strength without unfairness",
  "",
  "- Do not use whole-output inequality, “some output changed,” “some warning exists,” a nonempty exception, or a generic `has_issues` flag as the only proof of a required behavior. Assert the relevant public state, result, count, continuation, or effect directly.",
  "- When a contract defines counts, parse the complete count lines and assert the correct count. When it does not define the counting unit, assert detection and state/effect, or first define whether the unit is a field, item, rule, target, match, category, or operation.",
  "- Do not require one log record per issue, one repeated keyword, or one physical line per item unless the prompt specifies that granularity. Conversely, do not allow a single aggregate result to hide required independent findings when the prompt explicitly says to count/log each violation.",
  "- Test positive and negative cases independently. A mixed fixture with one valid and one invalid value can prove only that something happened; add an isolated valid case and an isolated invalid case when acceptance of the valid case matters.",
  "- For aliases, options, fields, formats, supported types, and backends, test each promised category or a justified representative matrix. Do not let a hard-coded subset pass because the visible examples cover only four fields, one backend, one selector, one alias, or one error path.",
  "- For multi-item or multi-field operations, assert that all required members are processed, that valid neighbors continue after a skippable invalid member, and that one failure does not silently short-circuit later required checks.",
  "- When testing a warning or diagnostic, capture the repository’s actual public channel and associate the message with the operation. Do not accept an unrelated log record, and do not require a literal word, exact field name, basename, punctuation, or stdout when the contract only requires a clear diagnostic.",
  "- If a message must identify a rule, target, field, or path, accept the contract’s alternatives (name, index, or equivalent location) and do not assume zero-based indexing, a dotted path, a particular vocabulary, or a fixed output layout.",
  "",
  "### Harness and fixture integrity",
  "",
  "- A test setup must be valid under the repository’s real public lifecycle. Do not create state outside the invocation/session that the prompt says owns it and then require an invocation-scoped recorder to observe it. Do not use stale model objects after the contract says pruning/removal permanently deletes them.",
  "- Do not omit required outer fields, use an invalid document shape, or combine an unrelated malformed field with the behavior under test. For example, a JSON test requiring successful import must include every prompt-required top-level list, and an ICS success fixture must be valid independently of the RRULE edge being tested.",
  "- Do not make a fake module or collaborator less capable than the real public object. Preserve valid exports, attributes, method signatures, model shapes, iterable/generator behavior, and state invariants. A fake that drops new fields, returns a list where the real API returns a generator, or changes import identity can reject a correct solution.",
  "- Patch the public boundary actually used by the application, or use a real isolated integration path. Do not patch `module.function` while the implementation may have a direct imported binding, patch one of several invented import paths, require a nonexistent future helper, or make success depend on a private `get_templates_dir`, loader, saver, or factory name.",
  "- A test must not require a specific pool API (`apply_async` versus `imap_unordered`), callback protocol, executor, scheduler, import style, or worker placement. Test prerequisite ordering, blocking, isolation, and failure propagation through a fair public boundary. Use deterministic latches for concurrency rather than inspecting a private `pending` map.",
  "- Do not drive a new UI by an ordinal iterator of answers, prompt keyword matching, exact confirmation-call count, or hard-coded free-text token unless that protocol is explicitly specified. A compliant implementation may use a menu, free text, a delimited selection, a separate confirmation, or another accessible flow.",
  "- Do not assume a detached constructor, unmounted screen, inactive editor, or fake collection has the same lifecycle effects as the production path. If the requirement is “while active,” open it through the real public path; if the requirement is a model behavior, test the model directly.",
  "- Shared helpers must not contain hidden assumptions that contaminate every test: fixed path lengths, presumed default filenames, required absolute paths, a particular editor implementation, a specific button traversal order, or a default format that the prompt does not define.",
  "",
  "### Public UI and interaction checks",
  "",
  "- Check visible, usable behavior through accessible labels, public actions, resulting state, and actual requests/effects. Do not count inert text in a script/template block as a rendered control, and do not require a particular DOM/widget class, layout, query order, coordinate, or internal model key.",
  "- Locate controls by stable public role/label or exercise them through user-visible navigation. Do not require a specific initial focus, Enter default, Tab order, Up/Down key, row order, button order, or that a successful action keeps a screen mounted unless the prompt or an established UI contract says so.",
  "- For selection tests, identify the intended row/action by its visible identity rather than assuming the second row is selected after one particular key. Assert both directions when the prompt requires both, and verify the selected item’s public identity, not merely the row index.",
  "- For status/error tests, clear or snapshot prior status so stale text cannot satisfy a later assertion. Capture stdout, stderr, structured events, and user-facing notifications according to the repository contract rather than choosing one stream arbitrarily.",
  "- For machine-readable output, parse events/fields structurally. Do not require a field to be top-level, an array rather than a mapping, a particular error key, a traceback key, a bytes-count interpretation, or a welcome payload flattening unless the prompt explicitly states that shape.",
  "- For destructive dialogs, assert that the warning communicates the required consequence and that Confirm/Cancel effects are correct. Do not require exact explanatory prose, initial focus, or a particular widget type.",
  "",
  "### Serialization, formats, and structured data",
  "",
  "- Assert required semantic fields and relationships while allowing valid extra fields, metadata, headers, separators, and equivalent serialization. Do not compare an entire object to the reference’s minimal form.",
  "- Do not assume an omitted option has a particular default format, algorithm, encoding, extension, output destination, or parser. Pass the option explicitly when the test is about another behavior, or state the default in the prompt before testing it.",
  "- Do not require a headerless file, zero physical lines, one exact newline form, lowercase digest hex, one field order, one RRULE prefix/case/order, or one Markdown/Taskpaper syntax when the contract permits equivalent representations. Parse the result and compare meaning.",
  "- When a format contract does require a schema, test the schema itself: required top-level fields, field types, list element types, valid/invalid enum values, round-trip preservation, and malformed stored data. Do not accidentally accept a missing required field or test only data created by the same implementation.",
  "- Test create, edit, load/show, list, validate, and externally corrupted storage separately when each is public. A create-time validator does not prove that `validate` reads stored corruption, and a parser that saves a file does not prove that a later process can reload it.",
  "- Failed edits, overwrite attempts, cross-format replacement, serialization failures, and editor cancellation must preserve the last valid representation when the prompt promises non-destructive behavior. Verify by reopening/reloading, not only by checking the immediate error.",
  '- For round trips, include falsey but meaningful values (`0`, `False`, `""` when allowed), `None` where distinct, non-ASCII text, malformed nested types, duplicate rows, optional fields, and fields with metadata. Avoid truthiness shortcuts in both implementation and assertions.',
  "",
  "### Validation, numeric, and schema boundaries",
  "",
  "- Test all required enforcement surfaces: direct assignment, construction/addition, modification, defaults, collection validation, CLI overrides, interactive prompts, serialization, reload, and each supported model type. Do not infer that one path covers another.",
  "- Distinguish missing, explicit null, blank/whitespace, empty container, false, zero, NaN, infinity, and a textual representation of each. A truthiness check must not reject valid `False`/`0` or accept malformed falsey input.",
  "- If the prompt requires finite numeric bounds or rejects numeric NaN, test both positive/negative infinity and NaN independently against minimum and maximum, including list members and configured bounds. Do not use ordinary comparison behavior as an unstated policy for non-finite values.",
  "- Use base-type normalization consistently for enum choices, bounds, defaults, native values, JSON values, BLOB/text values, aliases, dates, durations, and nullable numeric types. Test fractional numeric strings, epoch dates, boolean-valued options, Unicode case behavior, and canonicalization only when the prompt defines those semantics.",
  "- If invalid schemas must fail at construction, assert construction-time failure; if the prompt allows eager or lazy validation, accept either by triggering and observing the first required validation boundary. Do not accidentally test only one timing.",
  "- Test nested schemas recursively: native and JSON roots, nested JSON strings, typed list/dict descriptors, declared fields, dynamic dictionaries, required nested containers, defaults, invalid enum/schema names, cycles versus shared DAGs, depth limits, clone independence, empty explicitly supplied schemas, and CLI override integration.",
  "- Keep schema syntax and field grammar explicit. Do not invent bare mappings, sibling `type/schema` keys, reserved-field handling, enum aliases, extra top-level keys, or omitted-required defaults in a test unless the prompt states them.",
  "",
  "### Persistence, transactions, and state isolation",
  "",
  "- For every mutating operation, snapshot the important state before and after: database/model values, media/files, selected configuration, history, caches, output trees, and unaffected siblings. Unknown IDs, skipped entries, canceled actions, and invalid input must not mutate unrelated state.",
  "- Test all-or-nothing behavior across phases, not only a failure in the first phase. Force a later write to fail after an earlier repair/import/override has changed state, then use a fresh reader to verify complete rollback.",
  "- Test continuation where the contract says to skip one bad record and continue, including valid records before and after missing/invalid records. Do not accept a warning as proof that valid work was restored/imported.",
  "- Test no-op semantics independently: duplicate additions should not create data or undo/history entries; identical content should not cause unnecessary writes unless the contract requires a write; empty values should not be confused with omitted values.",
  "- Persist and reload through a fresh process/session/backend. A same-process object or a monkeypatched in-memory store can hide missing serialization, stale cache, remote-backend, or lifecycle behavior.",
  "- Cache tests must vary the requested input/path and invocation order. Do not let a stale cached inventory, profile, schema, or preset make a second operation observe the first operation’s data.",
  "- Backend-neutral history/snapshot tests must include complete remote state and backend-specific settings, not merely a serialized local reference/locator. Verify retention, sidecars, digests, encoding metadata, rollback, and update-target paths without requiring a private snapshot format.",
  "",
  "### Paths, filesystems, archives, and security",
  "",
  "- Test both lexical and resolved containment. Reject absolute paths, dot-segment escapes, drive/UNC forms, alternate separators, NUL/control forms, and symlink traversal through an in-root link to an outside location. Preserve existing outside files and avoid publishing partial trees.",
  "- Apply confinement consistently to list/read/create/update/delete, history tokens, profile/template names, playlist paths, archive members, extraction destinations, and selected archive views. A safe lexical path can still escape through a filesystem symlink.",
  "- Do not require safe inputs to be transformed into one particular spelling. For safe symlinks, backslashes, dot segments, or encoded names, compare resolved containment and semantic output unless the prompt defines canonical normalization. Separately test malicious forms where rejection is required.",
  "- For archive manifests, test manifest/archive bijection, type/path/size/mode/digest schemas, duplicate and normalized-collision paths, symlink target agreement, counters, ordering independence, malformed ZIPs, path hierarchy conflicts, and no-partial-extraction cleanup. Do not infer array-vs-map manifest shape or duplicate archive rejection unless specified.",
  "- Test missing, malformed, unreadable, externally corrupted, and symlinked storage. A valid filename or index name must not be treated as corruption merely because it matches a test fixture’s naming pattern.",
  "- Preserve encoding and text semantics. State UTF-8 or another codec before testing invalid bytes; include successful Unicode round trips as well as invalid-byte failures. Do not treat a valid U+FFFD filename as undecodable merely because it contains the replacement character.",
  "",
  "### Time, recurrence, and platform-sensitive behavior",
  "",
  "- Freeze or inject the clock for completion, expiration, age, timestamp, retry, and schedule tests. Never compare against independently sampled wall-clock values across a possible midnight/second boundary.",
  "- Test strict-after equality, due-before/due-after completion, month-end clamping, leap days, original calendar anchors across repeated cycles and reload, COUNT/UNTIL preservation and exhaustion, multiple comma-separated selectors, and all-day/aware/floating timezone behavior when the prompt promises them.",
  "- Preserve the prompt’s qualifier. A requirement about existing aware values does not automatically impose a changed wall time on floating values; a rule about actual completion time does not justify a pre-call timestamp; a rule about one format does not define another format’s error policy.",
  "- Compare recurrence schedules semantically or parse structured fields. Do not require an exact RRULE prefix, case, field order, minimal field set, natural-language alias spelling, formatter vocabulary, microsecond precision, or hidden anchor property unless explicitly specified.",
  "- Test both model and editor surfaces, persistence/reload, save/discard/undo, unsupported valid rules, destructive confirmation content, dirty-state propagation, and visible calendar highlighting through the real active view. Do not mutate a detached model and call that proof of UI synchronization.",
  "",
  "### Restricted expressions and resource limits",
  "",
  "- A “read-only” expression context must be genuinely non-mutable or mutation attempts must be rejected and reported according to the prompt. A deep copy alone is isolation, not immutability.",
  "- Test all documented bindings (`target`, `inventory`, `value`, `values`, target name) with successful reads, including wildcard and recursive matches. Do not assume mapping/list shapes, builtin availability, evaluation cardinality, or per-member count unless specified.",
  "- Test prohibited imports, file access, dangerous builtins, mutation through every binding, evaluation errors, recursion, infinite iterators, C-level loops, and later-rule isolation. A trace hook alone may not interrupt C-level work; use a process/resource boundary or reject dangerous constructs at load time if the prompt allows either.",
  "- Any pathological-expression test must have an unconditional finite timeout and a deterministic failure path. It must not hang, OOM, or rely on an externally configured environment variable to become safe.",
  "",
  "### Test runner and reporting integrity",
  "",
  "- Never use `--maxfail=1` or another fail-fast mode when the task requires complete diagnostics. Every real test must execute and appear in JUnit/report output; do not synthesize “missing test” failures after a wrapper aborts.",
  "- Bound every test-side growth loop, retry loop, subprocess, poll, and concurrency wait. If the required marker/result is not observed by the bound, fail that test with an explicit cause.",
  "- Keep test diagnostics honest. Separate infrastructure/setup failure, timeout/OOM, and implementation assertion failure. Do not classify a killed process as every individual test failing, and do not let an unrelated warning or stale status satisfy the current operation.",
  "- Avoid machine-dependent thresholds, platform-specific permissions, real network, mutable global state, and unseeded randomness unless the prompt explicitly requires them and the test controls the environment.",
  "",
  "### Gap-finder recurring fair-gap checklist",
  "",
  "When auditing a suite for missing behavioral coverage, deliberately consider these public branches when the prompt supports them:",
  "",
  "- noncanonical but meaningful values, falsey malformed values, Unicode/case variants, NaN/infinity, empty/zero values, nested and repeated inputs;",
  "- every public entry point and lifecycle: constructor/add/modify, direct/JSON/native, interactive/non-interactive, CLI/TUI, create/edit/load/show/list/validate, fresh reload/process, and all supported backends/formats;",
  "- defaults, aliases, requiredness, retry locality, blank versus interruption, cancellation/resume, duplicate no-ops, and invalid input side effects;",
  "- all declared fields rather than a hard-coded subset, all selector values/grammar branches, all target/path scopes, all independent siblings, and all transitive dependencies;",
  "- resolved data rather than raw files, cache misses and stale-cache changes, target identity versus display aliases, dotted/cross-platform names, and selected-target closure scope;",
  "- public counts, per-target attribution, summary completeness, structured diagnostics, correct output channels, and actual visible controls/effects rather than labels alone;",
  "- malformed stored data, failed later phases, atomic rollback, cross-format replacement, unknown IDs, missing records, remote/backend-specific state, sidecar integrity, and no partial artifacts;",
  "- real parallel execution, dependency gating, fetch ordering, failure propagation, deterministic public order/graph output, and cleanup of threads/processes/temporary files;",
  "- archive/playlist/template/profile path safety, symlink containment, separator variants, archive-manifest agreement, encoding, and successful Unicode paths;",
  "- recurrence/calendar anchor, strict-time, selector-list, COUNT/UNTIL, all-day/aware/floating, save/discard/undo, and active-UI highlight branches.",
  "",
  "For each candidate, still apply the fairness screen: the edge must be required or clearly public, the fixture must be valid, the observation must be public, and the assertion must not smuggle in a count unit, parser spelling, UI protocol, private API, harness shape, or timing threshold.",
].join("\n");

const SOLUTION_RULES_TEXT = [
  "# Gaps in solution",
  "",
  "This section describes defects in the implementation or solution behavior, even when the current tests pass. A solution gap must be grounded in an explicit prompt requirement, an established public contract, or a regression in observable repository behavior. Do not infer an `S` finding from a difference from `solution.patch`, a reference structure, a private helper, or a preferred architecture.",
  "",
  "## S<num> metrics for solution gaps",
  "",
  "`S` metrics classify implementation-side deficiencies. They are independent of `T` metrics: a weak test is a `T` finding, a wrong public behavior is an `S` finding, and one issue may legitimately have both. Use combined labels such as `S1/S2` when the defect affects both correctness and safety/integration.",
  "",
  "### S1 — behavioral correctness and compatibility",
  "",
  "The solution misses an explicit requirement, returns the wrong public value/state, loses data on a round trip, mishandles a required edge or entry point, violates a specified error/transition, or regresses established behavior. Examples include incomplete normalization, wrong recurrence/persistence semantics, missing root-level data, malformed input accepted, required invalid input ignored, or an existing non-interactive path broken.",
  "",
  "### S2 — safety, isolation, and integration correctness",
  "",
  "The solution leaves partial state after failure, violates transaction/rollback or dependency/concurrency boundaries, leaks state across invocations, mishandles backend/lifecycle integration, weakens path/security confinement, logs secrets, deadlocks, propagates data to the wrong scope, or otherwise makes a required operation unsafe or non-isolated. A defect can be S1 and S2 when it is both observably wrong and unsafe.",
  "",
  "### S3 — scope, maintainability, and repository quality",
  "",
  "The solution introduces unrelated changes, formatting churn, dead code, avoidable duplication, private coupling, unsupported API changes, architecture violations, or repository-quality regressions outside the requested behavior. Do not use S3 to penalize a merely different valid implementation; the issue must be concrete and externally or repository-observably harmful.",
  "",
  "## Solution implementation and test-authoring rules",
  "",
  "These rules describe what a high-quality solution and its tests must achieve. They are deliberately contract-first: a solution should be complete against the prompt and the repository's public behavior, not merely optimized to pass the currently visible examples.",
  "",
  "### 1. Implement the whole contract",
  "",
  "- Read the task sentence by sentence and map every explicit requirement, condition, prohibition, error case, state transition, side effect, and compatibility constraint to an implementation path and a meaningful test.",
  "- Treat the prompt as the specification and tests as evidence. Passing the supplied tests is necessary but not sufficient when the prompt contains behavior they do not exercise.",
  "- Before declaring completion, perform an adversarial pass: imagine a plausible shortcut that passes the obvious happy paths and check every boundary, empty/missing value, repeated operation, interacting feature, failure path, and state left behind.",
  "- Fix every concrete, reproducible contract gap and regression. Do not dismiss an externally observable mismatch as a minor edge case merely because the main path works.",
  "- Do not add behavior solely to satisfy a speculative reviewer preference, a reference implementation, or an ungrounded hypothetical. Improvements must remain within the stated contract and established repository behavior.",
  "",
  "### 2. Make new tests prove the solution",
  "",
  "- New feature tests should fail against the pre-solution implementation for the behavior they claim to cover and pass after the solution. A test that already passes before the feature is implemented is not evidence for that feature unless it is explicitly a regression test.",
  "- Assert the actual semantic result, not merely that execution completed, output changed, a word appeared somewhere, or a serializer returned something. Use independent expected data and nontrivial conversions so a pass-through or hardcoded shortcut cannot pass.",
  "- For mutations, verify both the intended new state and the important untouched state. Check no-op, unknown-ID, missing-record, invalid-input, cancellation, and failure paths for unintended writes or side effects.",
  "- For collections and batch operations, verify counts and contents when the contract specifies them, continuation after a skippable bad item when required, and that valid neighboring work is not lost.",
  "- Cover each public entry point that promises the behavior: direct and serialized input, interactive and non-interactive flows, create and edit, save and load, CLI and TUI, model and collection validation, and every supported backend or format.",
  "- Add interaction tests for requirements that combine features. A feature tested in isolation can still be wrong when defaults, retries, empty values, state transitions, or another required feature are present simultaneously.",
  "- Add negative tests for explicit guards and prohibitions: invalid configuration, forbidden writes, isolation boundaries, duplicate effects, invalid transitions, rollback boundaries, and dependent work after failure. Assert the required error/failure outcome and state preservation without pinning unspecified error wording.",
  "- Do not manufacture a passing test by calling the same implementation or serializer to produce the expected value, by asserting only whole-output inequality, or by checking private call counts when the public effect is the contract.",
  "- Keep tests fair under the rules above. A strong test suite catches materially wrong implementations without prescribing private names, mock shapes, pool APIs, source layout, or incidental formatting.",
  "",
  "### 3. Fit the existing architecture",
  "",
  "- Inspect real neighboring implementations before designing a new path. Reuse established public model, service, parser, transaction, configuration, logging, error, storage, and UI extension points where they fit.",
  "- Prefer the repository's public APIs over private fields, private helpers, direct database connections, internal event dictionaries, hidden callbacks, or reference-only module structure. If a public extension hook exists, use it rather than process-wide monkeypatching.",
  "- Keep responsibilities cohesive. Put parsing/normalization, domain behavior, persistence, command wiring, and presentation in the layers where the repository already keeps them. Do not put a large feature into one monolithic command, UI module, or unrelated existing file when the codebase uses focused modules.",
  "- Use focused helpers with clear contracts, but avoid needless wrapper layers, ad hoc `getattr()` fallbacks, duplicated option definitions, and special branches that exist only to adapt an avoidable design.",
  "- Centralize genuinely shared semantics—schema validation, path handling, date coercion, error formatting, serialization, or merge rules—so direct, interactive, load, and save paths cannot silently diverge. Expose a suitable public/shared helper rather than coupling unrelated classes to a private method.",
  "- Remove unused helpers, imports, constants, temporary scaffolding, dead branches, and unrelated edits before completion. A feature patch should be reviewable and narrowly scoped.",
  "",
  "### 4. Preserve behavior and make failures safe",
  "",
  "- Run the complete relevant regression suite as well as the new feature tests. Existing behavior, defaults, public APIs, and compatibility paths must remain intact unless the prompt explicitly changes them.",
  "- Use the repository's normal exception and logging patterns. Catch only expected failures, report them consistently to users, and do not use broad `except Exception` blocks that hide programming errors or turn distinct failures into misleading messages.",
  "- Validate at the correct boundary and validate all relevant representations. Reject malformed configuration, wrong types, invalid schemas, falsey-but-invalid values, bad aliases, and invalid serialized content when the contract requires rejection; do not defer a required validation until an unrelated later operation.",
  "- Ensure save-time and load-time validation are symmetric. Data accepted by one entry point must have the same semantics when serialized and read back, and corrupted stored data must follow the documented recoverable/error policy.",
  "- For multi-step database or state mutations, use the existing transaction/rollback mechanism when the contract requires an atomic operation. A late failure must not leave an unexplained partial repair, rollback, import, migration, or batch update.",
  "- For file replacement, validate before modifying the destination and use the repository's atomic temporary-file/replacement pattern where preservation matters. Failed creation, editing, replacement, or serialization must not destroy the last valid file.",
  "- Enforce locks and concurrency boundaries consistently. Unknown identifiers, skipped records, rejected inputs, canceled operations, and failed prerequisites must not mutate unrelated state. Perform dependent side effects only after the prerequisite operation has succeeded.",
  "- Preserve backend-neutral semantics. A snapshot must contain the complete state needed to restore every supported backend, including remote values when the prompt promises historical values—not merely a local locator or configuration dump.",
  "",
  "### 5. Keep all paths semantically consistent",
  "",
  "- Interactive and non-interactive conversion must apply the same normalization, schema, requiredness, default, blank-value, and error rules unless the prompt explicitly distinguishes them.",
  "- The same applies across JSON/native input, constructor/default application, collection validation, rendering, serialization/deserialization, CLI/TUI, and create/edit/load flows. Do not let one layer accept a value that a later layer rejects unexpectedly.",
  "- Validate aliases independently before choosing a preferred alias. Do not let a valid `visibility` mask an invalid `class`, or let a truthiness check allow an invalid falsey value through.",
  "- Normalize only what the contract requires. When it does require normalization, apply it consistently at every entry point and preserve repository invariants such as path separators, case-insensitive extensions, all-day exclusive end dates, timezone-aware values, newline state, encoding, and canonical enum forms.",
  "- Keep defaults and retries stable across the initial prompt and retry prompt. An explicit blank, cancellation, default-on-Enter rule, and invalid answer must follow the same documented policy after a retry as before it.",
  "- Preserve required information through round trips. Do not lose fields, metadata, ordering, duplicate policy, timezone components, remote content, or trailing-newline state merely because one implementation representation is convenient.",
  "",
  "### 6. Handle paths, formats, and boundaries defensively",
  "",
  "- Treat paths as untrusted input. Normalize both platform separator styles before interpreting them, reject traversal and absolute escapes, constrain resolution to the configured root, and apply the same safety rules to list, read, create, update, and delete operations.",
  "- If a format or extension is specified as case-insensitive, perform case-insensitive resolution on case-sensitive filesystems as well as case-insensitive ones. Define deterministic behavior when equivalent sibling names coexist rather than depending on directory iteration order.",
  "- Use the repository's existing parser and model invariants for dates, recurrence, calendars, events, and structured formats. Hand-rolled parsing should not silently accept values the established parser rejects or lose timezone/all-day/encoding information.",
  "- Preserve meaningful text differences, including an end-of-file newline when the contract cares about it. Diff, merge, and serialization code must distinguish content equality from a representation that merely looks equal after lossy splitting or normalization.",
  "- Treat empty, null, zero, missing, malformed, Unicode, unusually large, duplicate, and repeated values according to the prompt—not according to a convenient truthiness check or an accidental default.",
  "",
  "### 7. State, concurrency, and resource discipline",
  "",
  "- Avoid mutable process-global state for feature state, cached arguments, active sessions, monkeypatches, or dependency injection. If a framework requires shared state, scope it explicitly, restore it after the operation, and provide a lifecycle/unhook path.",
  "- Do not mutate live configuration or model objects temporarily without a reliable `try/finally` restoration. Prefer copies or explicit context objects, and ensure one invocation cannot leak into a later in-process invocation or test.",
  "- Use one canonical identity and one canonical dependency graph for discovery, validation, closure expansion, visualization, and execution. Do not validate using inventory keys and execute using a different field such as `vars.target` unless the mapping is explicit and guaranteed.",
  "- For dependency scheduling, resolve all transitive prerequisites, reject missing targets and cycles before work starts, preserve deterministic ordering where promised, run only ready work, block dependents after prerequisite failure, and use the same dependency constraints in serial and parallel modes.",
  "- Do not turn an implementation-specific pool API, callback order, or thread event into the behavioral contract. At the same time, do not weaken the actual failure/isolation guarantees: no dependent may run early, no forbidden work may occur, and all required independent work must follow the prompt's stated failure policy.",
  "- Retain existing deduplication, cache reuse, batching, and parallelism behavior unless the prompt changes it. Avoid creating a new temporary cache or serial worker for every target when shared grouping is part of the existing behavior or causes an avoidable performance regression.",
  "- Bound untrusted or potentially expensive work without claiming that a shallow copy is immutable or that `eval` plus a trace hook is a secure sandbox. Use a genuinely read-only context, restrict accessible operations, and choose a resource-control mechanism that cannot corrupt global interpreter state when the security contract matters.",
  "- Use iterative processing or bounded recursion for large imports, graphs, inventories, and batches. Clean up threads, temporary files, locks, and callbacks on success, failure, and cancellation.",
  "",
  "### 8. User-facing CLI and UI quality",
  "",
  "- Follow the project's existing command and UI architecture rather than adding unrelated inline styling, imperative flows, deeply nested closures, or global changes to shared input primitives when a focused extension is available.",
  "- Match the exact interaction contract. If the prompt allows only `y`/`n`, exact words, or enumerated choices, reject aliases and blank/default responses unless the prompt explicitly permits them. Make cancellation and interruption behavior consistent at every branch, including the initial, empty-state, retry, and creation paths.",
  "- Keep destructive, overwrite, merge, repair, and rollback operations explicit and recoverable. Do not silently choose a default that the contract requires the user to choose, and do not leave a partially modified UI or persisted state after cancellation or failed confirmation.",
  "- Keep user-facing errors consistent in channel, status, response shape, and actionable content. Use the established error type/logger/HTTP response pattern rather than mixing generic abort pages, raw exceptions, and custom payloads without a contract reason.",
  "- Avoid unrequested UI shortcuts, automatic matching, hidden text, extra commands, or unrelated feature changes. They increase maintenance surface and can create behavior that conflicts with existing workflows.",
  "- Treat warnings from the project's UI/toolkit tests as real quality issues when they indicate invalid sizing, layout, focus, or resource usage. Do not declare a polished UI while the implementation emits avoidable runtime warnings.",
  "",
  "### 9. Security, privacy, and compatibility gate",
  "",
  "- Do not log raw secrets, CLI override values, variable-file values, preset contents, passwords, tokens, or other sensitive values at any log level. Tests should use distinctive sentinels and inspect logs/display diagnostics without requiring exact safe wording.",
  "- Preserve existing public behavior outside the feature: fixed-field deletion, non-interactive overwrite, legacy/simple recurrence compatibility, optional feature-disabled paths, selected backend behavior, and normal error/transaction semantics.",
  "- Do not introduce unrelated formatting churn, refactors, comments removals, metadata edits, helper rewrites, or changes to vdir/transaction/storage behavior merely because a feature touches a neighboring file. Keep the diff narrow and repository-formatted.",
  "- Do not claim a top-quality score while known regressions remain in an untested alternate backend, fresh process, cross-format path, supported alias, all-day/floating case, parallel path, or public UI surface. Fix concrete caveats rather than explaining them away as edge cases.",
  "",
  "### 10. Full-quality completion gate",
  "",
  "A solution is ready for a highest-quality review only when all of the following are true:",
  "",
  "- every prompt requirement has a deliberate implementation path;",
  "- every important public path has an independent behavioral test;",
  "- new tests fail for the intended reason before the solution and pass afterward;",
  "- baseline and regression tests remain green;",
  "- no known public behavior differs across equivalent entry points without an explicit reason;",
  "- invalid input and failure paths are safe, consistent, and non-destructive;",
  "- persistence and multi-step mutations preserve valid prior state or roll back as required;",
  "- concurrency and lifecycle state cannot leak across operations;",
  "- the implementation uses repository conventions and public extension points;",
  "- there is no dead code, unrelated change, avoidable duplication, or hidden implementation coupling; and",
  "- remaining review notes are either fixed or explicitly shown to be outside the contract rather than silently ignored.",
].join("\n");

export function loadTestGuidelines(): string {
  return GUIDELINES_TEXT.trim();
}

/** The `# Fairness vs. unfairness` rules from rules.md. */
export function loadFairnessRules(): string {
  return FAIRNESS_RULES_TEXT.trim();
}

/** The `# Gaps in tests` rules from rules.md. */
export function loadGapRules(): string {
  return GAP_RULES_TEXT.trim();
}

/** The `# Gaps in solution` rules from rules.md. */
export function loadSolutionRules(): string {
  return SOLUTION_RULES_TEXT.trim();
}
